version: "3"
services:
  redis:
    image: redis
    ports:
      - "6379:6379"

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    env_file:
      - db.env
    # volumes:
    # - ./migrations/0-enable_uuid_v4.sql:/docker-entrypoint-initdb.d/init.sql
